name: Deploy to Production
on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to deploy (e.g., v1.2.3)'
        required: true
        type: string

jobs:
  deploy-prod:
    name: Deploy to Production
    uses: projet-ccm2/shared-workflows/.github/workflows/nodejs-cd.yml@main
    if: github.event_name != 'pull_request'
    with:
      required_env_vars: GCP_SA_KEY,GCP_PROJECT_ID,TWITCH_CLIENT_ID,AUTH_SERVICE_URL,ACHIEVEMENT_MANAGEMENT_SERVICE_URL,API_SERVICE_URL,FRONT_URL
      docker-image-name: front-prod
      docker-tag: ${{ github.event.inputs.version || github.ref_name || format('prod-{0}', github.sha) }}
      artifact-registry-repository: 'front-docker-prod'
      environment: production
      cloud-run-service-name: front-prod
      cloud-run-port: '4173'
      service_type: "front"

    secrets:
      GCP_SA_KEY: ${{ secrets.PROD_GCP_SA_KEY }}
      GCP_PROJECT_ID: ${{ secrets.PROD_GCP_PROJECT_ID }}
      TWITCH_CLIENT_ID: ${{ secrets.PROD_TWITCH_CLIENT_ID }}
      AUTH_SERVICE_URL: ${{ secrets.PROD_AUTH_SERVICE_URL }}
      ACHIEVEMENT_MANAGEMENT_SERVICE_URL: ${{ secrets.PROD_ACHIEVEMENT_MANAGEMENT_SERVICE_URL }}
      API_SERVICE_URL: ${{ secrets.PROD_API_SERVICE_URL }}
      FRONT_URL: ${{ secrets.PROD_FRONT_URL }}
